version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s / %(levelname)s / %(message)s'

handlers:
  console:
    class: rich.logging.RichHandler
    level: INFO
    rich_tracebacks: True
    markup: True
    show_time: False
    show_path: False

  warning_file_handler:
    class: logging.FileHandler
    level: WARNING
    formatter: simple
    filename: "data/08_reporting/warnings.log"
    mode: "w"

loggers:
  kedro:
    handlers: [console]
    level: INFO
    propagate: False

  __main__:
    handlers: [console]
    level: INFO
    propagate: False

  scheduling_engine:
    handlers: [console]
    level: INFO
    propagate: False

root:
  handlers: [console, warning_file_handler]
  level: INFO
