name: Fetch updates from parent repository

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  fetch-updates:
    runs-on: ubuntu-latest

    steps:
    - name: Clone other repository
      run: |
        git clone https://x-access-token:${{ secrets.EPSILON_PAT }}@github.com/brightcape/EIT_Epsilon_000511.git
      env:
        TOKEN: ${{ secrets.EPSILON_PAT }}

    - name: Change directory and fetch updates
      run: |
        git config --global user.email "j.oudshoorn@brightcape.nl"
        git config --global user.name "JeanLuc Oudshoorn"
        git fetch ../EIT_Epsilon_000511
        git checkout test
        git merge origin/test --strategy-option=theirs --no-commit
        git checkout HEAD -- src/eit_epsilon/pipelines/scheduling_engine conf/base/parameters_genetic_algo.yml conf/base/parameters_scheduling.yml
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Merge updates from parent repository"
          git push origin test
        fi
