name: Sync Fork

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: test

    - name: Sync changes
      env:
        TOKEN: ${{ secrets.EPSILON_PAT }}
      run: |
        git remote add parent_repo https://x-access-token:$TOKEN@github.com/brightcape/EIT_Epsilon_000511.git
        git config --global user.email "j.oudshoorn@brightcape.nl"
        git config --global user.name "JeanLuc Oudshoorn"
        git fetch parent_repo
        git checkout parent_repo/test
        git checkout test src/eit_epsilon/pipelines/scheduling_engine/nodes.py
        git commit -m "Update parent repo" --no-verify
        git push parent_repo HEAD:fork_connection_test --force
