name: Fetch updates from parent repository

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  fetch-updates:
    runs-on: ubuntu-latest

    steps:
    - name: Clone remote repository
      run: |
        git clone https://x-access-token:${{ secrets.EPSILON_PAT }}@github.com/brightcape/EIT_Epsilon_000511.git
      env:
        TOKEN: ${{ secrets.EPSILON_PAT }}

    - name: Change directory and fetch updates
      run: |
        cd EIT_Epsilon_000511
        git fetch origin test
        git checkout test
        git merge origin/test --strategy-option=theirs --no-commit
        git checkout HEAD -- src/eit_epsilon/pipelines/scheduling_engine conf/base/parameters_genetic_algo.yml conf/base/parameters_scheduling.yml
        git commit -m "Merge updates from parent repository"
        git push origin test
