name: Fetch updates from parent repository

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  fetch-updates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Fetch updates from parent repository
      run: |
        git remote add parent https://github.com/brightcape/EIT_Epsilon_000511.git
        git fetch parent test
        git checkout test
        git config --global user.email "j.oudshoorn@brightcape.nl"
        git config --global user.name "JeanLuc Oudshoorn"
        git merge parent/test --strategy-option=theirs --no-commit
        git checkout HEAD -- src/eit_epsilon/pipelines/scheduling_engine conf/base/parameters_genetic_algo.yml conf/base/parameters_scheduling.yml
        git commit -m "Merge updates from parent repository"
      env:
        TOKEN: ${{ secrets.EPSILON_PAT }}
