name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Sync changes
      env:
        TOKEN: ${{ secrets.EPSILON_PAT }}
      run: |
        git remote add upstream https://x-access-token:$TOKEN@github.com/brightcape/EIT_Epsilon_000511.git

    - name: Set up Git
      run: |
        git config --global user.email "j.oudshoorn@brightcape.nl"
        git config --global user.name "JeanLuc Oudshoorn"

    - name: Push folder to upstream
      run: |
        git checkout -b temp-branch
        git add src/eit_epsilon/pipelines/scheduling_engine/*
        git commit -m "Push changes from src/eit_epsilon/pipelines/scheduling_engine"
        git push upstream temp-branch:main